spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thukabjj/microservices/
          username: thukabjj
          password: M0d0rus3r321@
          label: master
          searchPaths:
            - 'ms-config-properties/{application}/{profile}'
management:
  security:
    enabled: false