spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thukabjj/ms-config-properties/
          username: thukabjj
          password:
          label: master
          searchPaths:
            - '/{application}/{profile}'
management:
  security:
    enabled: false